language: cpp
compiler: gcc
os: osx
before_install:
  - pip install --user cpp-coveralls
script:
  - cmake -S . -B build -DCMAKE_CXX_FLAGS="-ftest-coverage -fprofile-arcs" -DINSTALL_DEPS=true
  - make -C build
  - ./expert_system_tests
after_success:
  ~/Library/Python/2.7/bin/cpp-coveralls --root . -i src -i include -E ".*CMakeFiles.*" --exclude include/argparse/argparse.hpp