language: cpp
compiler: gcc
os: osx
addons:
  homebrew:
    packages:
      - glew
before_install:
  - pip install --user cpp-coveralls
script:
  - cmake -DCMAKE_CXX_FLAGS="-ftest-coverage -fprofile-arcs" .
  - make
  - ./expert_system_tests
after_success:
  ~/Library/Python/2.7/bin/cpp-coveralls --root . -i src -i include -E ".*CMakeFiles.*" --exclude include/argparse/argparse.hpp