language: cpp
compiler: clang
os: osx
osx_image: xcode11.3
before_install:
  - pip install --user cpp-coveralls
script:
  - cmake -S . -B build -DCMAKE_CXX_FLAGS="-ftest-coverage -fprofile-arcs" -DINSTALL_DEPS=true
  - make -C build
  - ./expert_system_tests
after_success:
  ~/Library/Python/2.7/bin/cpp-coveralls --root . -i include/Expressions -i include/ExpertSystem.hpp -i include/ExpertSystemData.hpp -i src/ExpertSystemLib -e src/ExpertSystemLib/Parse/Lexer.lex -e src/ExpertSystemLib/Parse/Grammar.yacc